created basic UI with Bootstrap/Thymeleaf
sysc4806/SYSC4806-WDWH pull request #27
Opened 2019-02-23 23:42 UTC by K-shamG

I figured you should all review this one since it's da look. 
Here's a pic, but you should pull this branch (StaticUI) and take a look on your own computer as well: 
![image](https://user-images.githubusercontent.com/15951317/53293013-13e86780-379a-11e9-8a03-e9d8dbdd00d6.png)

A lot of this commit is bootstrap stuff. You really just need to look at: 
- HomeController (created to test the view, this can be altered when the actual controllers are made)
- index.html
- index.css
- index.js

(Once this is merged, we can check #2)

2019-02-23 23:56 UTC, RyanWork commented on src/main/java/SYSC4806/HomeController.java
> +package SYSC4806;
I think we should also have some controllers package. Might as well add it on this feature since it's using the first controller -shrug-

2019-02-24 00:03 UTC, RyanWork commented on src/main/resources/templates/index.html
> +        });
I mean if I'm being a butthole, I would suggest adding a comment here. It's not entirely clear what this is (although I know you're trying to configure the fancy dropdowns when it loads :P )

2019-02-24 00:05 UTC, RyanWork requested changes
Looks okay to me, just requesting some really small changes. I'm good with how it looks. We can always change it later.

2019-02-24 00:40 UTC, RyanWork approved these changes

2019-02-24 01:37 UTC, SupriyaGadigone commented
Looks good to me

2019-02-24 01:37 UTC, SupriyaGadigone approved these changes

2019-02-25 20:57 UTC, andrewdlqnguyen commented
looks good to me too :D

2019-02-25 21:00 UTC, andrewdlqnguyen approved these changes
looks good! bootstrap is a blessing

2019-02-25 22:46 UTC, adamstaples approved these changes
Everything looks good to me! Good job!

2019-02-25 23:25 UTC, merged