Models connecting as per Issue #5
sysc4806/SYSC4806-WDWH pull request #29
Opened 2019-02-25 01:06 UTC by SupriyaGadigone

Working on #18. Is there more to it than this?
I wanted to write some tests cases on this too but I guess I need the repositories to be merged so I can do it after.

2019-02-25 14:16 UTC, K-shamG requested changes
As you said, we need to wait for Ryan's pull request to get merged before you can test it. We can have someone work on testing this branch with you, but I'd prefer to have tests written before it's merged since this is a crucial part to having it work.

2019-02-25 14:16 UTC, K-shamG commented on src/main/java/SYSC4806/Model/Course.java
> +    @ManyToMany
Referencing https://www.baeldung.com/spring-data-rest-relationships, I think this needs to have a CascadeType.ALL and it looks like they use @JoinTable to create that intermediary table for many to many relationships.

2019-02-25 14:16 UTC, K-shamG commented on src/main/java/SYSC4806/Model/Program.java
> +    @OneToMany
I believe this should be a @ManyToMany as a course can belong to many programs (also in Course, you specified this relationship as such). Following the same tutorial, I think this needs a @mappedBy attribute.

2019-02-25 14:16 UTC, K-shamG commented on src/main/java/SYSC4806/Model/LearningOutcome.java
> +    @ManyToMany
In category, you have it listed as one-to-many. A learning outcome only maps to one category; this should be a many-to-one.

2019-02-26 18:29 UTC, RyanWork commented
#25 is merged now. You can try implementing it now as Kshamina said

2019-02-27 02:33 UTC, SupriyaGadigone commented
Bunch of things changed here:
1. The data type for the entities were ArrayList before so I had to change it to List since ArrayList is not supported (https://stackoverflow.com/questions/44157641/which-collections-are-supported-by-hibernate-manytomany-annotation)
2. In the LearningOutcome class the category had to be changed from a List to just Category since its @ManyToOne mapping (followed kshamina's link https://www.baeldung.com/spring-data-rest-relationships)  
3. Added the META-INF folder with persistence.xml file

Sorry guys, I dont know how I missed all of this basic stuff, I will follow the labs properly from next time 

Anyways, next up will be tests for all of this.

2019-02-28 00:18 UTC, K-shamG approved these changes
I'm good with this for now since I see tests are in another issue. It can always be modified after testing.

2019-02-28 02:56 UTC, RyanWork approved these changes

2019-02-28 17:58 UTC, SupriyaGadigone commented
Bunch of things here:
- Fixed the mappings as per the tests 
- The tests are very basic where they test all the methods in the Repository classes created by Ryan. I am basically just creating dummy objects, saving them and then testing if they persist to see if the mappings work.

We can add more tests after as well.

2019-02-28 17:59 UTC, SupriyaGadigone commented
Also, if you don't want to test it yourself, proof that the test passed :P 
![screen shot 2019-02-28 at 12 49 34 pm](https://user-images.githubusercontent.com/15680487/53587562-b6b53300-3b58-11e9-84ed-8c132a0d11fe.png)

2019-02-28 20:11 UTC, RyanWork commented
I think we should consider initializing some properties in our empty constructor. Whether or not this is null (or a default of some primitive), it doesn't hurt to do that? For example, we might want to initialize the Lists<> to a default empty list and not necessarily leave it null. We could call the default constructors like:
```java
public Course(){
    this.Course(0, null, null, new ArrayList<LearningOutcome>(), new ArrayList<Program>());
}
```

2019-02-28 20:30 UTC, RyanWork approved these changes

2019-02-28 20:59 UTC, andrewdlqnguyen approved these changes

2019-02-28 21:02 UTC, merged