Years Select
sysc4806/SYSC4806-WDWH pull request #83
Opened 2019-03-26 19:20 UTC by K-shamG

Changed year select to update when program is selected (some classes don't apply to all years)

Closes #56

2019-03-26 21:06 UTC, andrewdlqnguyen approved these changes
Looks good

2019-03-28 13:21 UTC, RyanWork commented on src/main/java/SYSC4806/Controller/HomeController.java
> +    public ResponseEntity<Object> getYears(@PathVariable("program") String p) {
Looks okay, can you just add some documentation on this method?

2019-03-28 13:22 UTC, RyanWork commented on src/main/resources/static/js/index.js
> +$('#programSelect').change( function() {
Can you also add some documentation just saying what you're binding this event-handler to. I don't think it's entirely intuitive just from looking at what's going on in here.

2019-03-28 13:23 UTC, RyanWork requested changes
Functions well :) Just some dev comments please!

2019-03-28 15:11 UTC, merged